[project]
name = "pkit"
version = "0.1.0"
description = "A simple CLI tool to snapshot, track, and scan installed Python packages."
authors = [{ name = "ReRa0", email = "adamkimkh@gmail.com" }]
dependencies = []

[project.scripts]
pkit = "pkit.cli:main"